<?php

global $states;

$states['GN'] = [
'BEYLA'       => __( 'Beyla', 'idonate' ),
'BOFFA'       => __( 'Boffa', 'idonate' ),
'BOKE'        => __( 'Boke', 'idonate' ),
'CONAKRY'     => __( 'Conakry', 'idonate' ),
'COYAH'       => __( 'Coyah', 'idonate' ),
'DABOLA'      => __( 'Dabola', 'idonate' ),
'DALABA'      => __( 'Dalaba', 'idonate' ),
'DINGUIRAYE'  => __( 'Dinguiraye', 'idonate' ),
'DUBREKA'     => __( 'Dubreka', 'idonate' ),
'FARANAH'     => __( 'Faranah', 'idonate' ),
'FORECARIAH'  => __( 'Forecariah', 'idonate' ),
'FRIA'        => __( 'Fria', 'idonate' ),
'GAOUAL'      => __( 'Gaoual', 'idonate' ),
'GUECKEDOU'   => __( 'Gueckedou', 'idonate' ),
'KANKAN'      => __( 'Kankan', 'idonate' ),
'KEROUANE'    => __( 'Kerouane', 'idonate' ),
'KINDIA'      => __( 'Kindia', 'idonate' ),
'KISSIDOUGOU' => __( 'Kissidougou', 'idonate' ),
'KOUBIA'      => __( 'Koubia', 'idonate' ),
'KOUNDARA'    => __( 'Koundara', 'idonate' ),
'KOUROUSSA'   => __( 'Kouroussa', 'idonate' ),
'LABE'        => __( 'Labe', 'idonate' ),
'LELOUMA'     => __( 'Lelouma', 'idonate' ),
'LOLA'        => __( 'Lola', 'idonate' ),
'MACENTA'     => __( 'Macenta', 'idonate' ),
'MALI'        => __( 'Mali', 'idonate' ),
'MAMOU'       => __( 'Mamou', 'idonate' ),
'MANDIANA'    => __( 'Mandiana', 'idonate' ),
'NZEREKORE'   => __( 'Nzerekore', 'idonate' ),
'PITA'        => __( 'Pita', 'idonate' ),
'SIGUIRI'     => __( 'Siguiri', 'idonate' ),
'TELIMELE'    => __( 'Telimele', 'idonate' ),
'TOUGUE'      => __( 'Tougue', 'idonate' ),
'YOMOU'       => __( 'Yomou', 'idonate' ),
];
