<?php
/**
 * Philippines provinces
 *
 * @category    i18n
 */
global $states;

$states['PH'] = [
    'MM'  => __( 'Metro Manila', 'idonate' ),
    'ABR' => __( 'Abra', 'idonate' ),
    'APA' => __( 'Apayao', 'idonate' ),
    'IFU' => __( 'Ifugao', 'idonate' ),
    'KAL' => __( 'Kalinga', 'idonate' ),
    'MOU' => __( 'Mountain Province', 'idonate' ),
    'ILN' => __( 'Ilocos Norte', 'idonate' ),
    'ILS' => __( 'Ilocos Sur', 'idonate' ),
    'LUN' => __( 'La Union', 'idonate' ),
    'PAN' => __( 'Pangasinan', 'idonate' ),
    'BTN' => __( 'Batanes', 'idonate' ),
    'CAG' => __( 'Cagayan', 'idonate' ),
    'ISA' => __( 'Isabela', 'idonate' ),
    'NUV' => __( 'Nueva Vizcaya', 'idonate' ),
    'QUI' => __( 'Quirino', 'idonate' ),
    'AUR' => __( 'Aurora', 'idonate' ),
    'BAN' => __( 'Bataan', 'idonate' ),
    'BUL' => __( 'Bulacan', 'idonate' ),
    'NUE' => __( 'Nueva Ecija', 'idonate' ),
    'PAM' => __( 'Pampanga', 'idonate' ),
    'TAR' => __( 'Tarlac', 'idonate' ),
    'ZMB' => __( 'Zambales', 'idonate' ),
    'BTG' => __( 'Batangas', 'idonate' ),
    'CAV' => __( 'Cavite', 'idonate' ),
    'LAG' => __( 'Laguna', 'idonate' ),
    'QUE' => __( 'Quezon', 'idonate' ),
    'RIZ' => __( 'Rizal', 'idonate' ),
    'MAD' => __( 'Marinduque', 'idonate' ),
    'MDC' => __( 'Occidental Mindoro', 'idonate' ),
    'MDR' => __( 'Oriental Mindoro', 'idonate' ),
    'PLW' => __( 'Palawan', 'idonate' ),
    'ROM' => __( 'Romblon', 'idonate' ),
    'ALB' => __( 'Albay', 'idonate' ),
    'CAN' => __( 'Camarines Norte', 'idonate' ),
    'CAS' => __( 'Camarines Sur', 'idonate' ),
    'CAT' => __( 'Catanduanes', 'idonate' ),
    'MAS' => __( 'Masbate', 'idonate' ),
    'SOR' => __( 'Sorsogon', 'idonate' ),
    'AKL' => __( 'Aklan', 'idonate' ),
    'ANT' => __( 'Antique', 'idonate' ),
    'CAP' => __( 'Capiz', 'idonate' ),
    'GUI' => __( 'Guimaras', 'idonate' ),
    'ILI' => __( 'Iloilo', 'idonate' ),
    'NEC' => __( 'Negros Occidental', 'idonate' ),
    'BOH' => __( 'Bohol', 'idonate' ),
    'CEB' => __( 'Cebu', 'idonate' ),
    'NER' => __( 'Negros Oriental', 'idonate' ),
    'SIG' => __( 'Siquijor', 'idonate' ),
    'BIL' => __( 'Biliran', 'idonate' ),
    'EAS' => __( 'Eastern Samar', 'idonate' ),
    'LEY' => __( 'Leyte', 'idonate' ),
    'NSA' => __( 'Northern Samar', 'idonate' ),
    'WSA' => __( 'Samar', 'idonate' ),
    'SLE' => __( 'Southern Leyte', 'idonate' ),
    'ZAN' => __( 'Zamboanga del Norte', 'idonate' ),
    'ZAS' => __( 'Zamboanga del Sur', 'idonate' ),
    'ZSI' => __( 'Zamboanga Sibugay', 'idonate' ),
    'BUK' => __( 'Bukidnon', 'idonate' ),
    'CAM' => __( 'Camiguin', 'idonate' ),
    'LAN' => __( 'Lanao del Norte', 'idonate' ),
    'MSC' => __( 'Misamis Occidental', 'idonate' ),
    'MSR' => __( 'Misamis Oriental', 'idonate' ),
    'COM' => __( 'Compostela Valley', 'idonate' ),
    'DAV' => __( 'Davao del Norte', 'idonate' ),
    'DAS' => __( 'Davao del Sur', 'idonate' ),
    'DAC' => __( 'Davao Occidental', 'idonate' ),
    'DAO' => __( 'Davao Oriental', 'idonate' ),
    'NCO' => __( 'Cotabato', 'idonate' ),
    'SAR' => __( 'Sarangani', 'idonate' ),
    'SCO' => __( 'South Cotabato', 'idonate' ),
    'SUK' => __( 'Sultan Kudarat', 'idonate' ),
    'AGN' => __( 'Agusan del Norte', 'idonate' ),
    'AGS' => __( 'Agusan del Sur', 'idonate' ),
    'DIN' => __( 'Dinagat Islands', 'idonate' ),
    'SUN' => __( 'Surigao del Norte', 'idonate' ),
    'SUR' => __( 'Surigao del Sur', 'idonate' ),
    'BAS' => __( 'Basilan', 'idonate' ),
    'LAS' => __( 'Lanao del Sur', 'idonate' ),
    'MAG' => __( 'Maguindanao', 'idonate' ),
    'SLU' => __( 'Sulu', 'idonate' ),
    'TAW' => __( 'Tawi-tawi', 'idonate' ),
];
